### ISSUE TITLE
выбрать карту и подобрать координаты

### ISSUE THREAD

**Issue by epexa** [epexa/forestspace.eu#14]
- [x] нужно определиться какую карту взять Yandex или Google и какой слой.
- [x] далее сделать список координат.

**Comment by knopf127** [comment]
яндекс карта криво показывает картинку зд и там нет панорамы никакой

**Comment by epexa** [comment]
**@knopf127 нужен список координат для этих мифов:**

- лихо
- принц и ведьма
- леший
- пасечник
- живые улья
- зозовка
- вегетандры
- каменный круг
- королева деревьев
- пущевик
- русалки
- яга
- водяной

**в формате "23.93218827226301, 52.68400095664496"**

**Comment by knopf127** [comment]
марена -  владения Марены не показаны на карте, не имеют географической отметины.
места силы
лихо - 52.556165, 24.045836
принц и ведьма
леший - 52.594988, 24.023551
пасечник - 52.540947, 23.897788
живые улья
зозовка
вегетандры
каменный круг
королева деревьев - 52.619694, 23.977718
пущевик - 52.574028, 23.927132
русалки - 52.629858, 23.864176
яга - 52.580984, 23.896866
водяной

**Comment by epexa** [comment]
по поводу марены как вариант каждый раз рандомно ставить точку на карте в пределах пущи

**Comment by knopf127** [comment]
можно точкой на карте, и с вопросом вместо уникальной картинки  - типо неопознанное местоположение, как вам?
