### ISSUE TITLE
добавить описание членам команды

### ISSUE THREAD

**Issue by epexa** [epexa/forestspace.eu#2]

**Comment by knopf127** [comment]
https://www.facebook.com/khlebus.ariana
Arina Khlebus
web-designer

Waleria Waszczyłko
https://www.facebook.com/profile.php?id=100011709130979
Polish language interpreter

Victoria Goncharova
https://www.facebook.com/victoriassecret016
marketing and SMM

Lesya Pchelka
https://www.facebook.com/lesyapchelka
archive photo specialist

Erlan Shendavletov
https://www.facebook.com/erlan.kotov
web-developer

https://www.facebook.com/maria.knop.3
Maria Knop
project manager
