### ISSUE TITLE
Подобрать аудио для сайта

### ISSUE THREAD

**Issue by arkhleb** [epexa/forestspace.eu#3]
Магические эффекты, шум леса, звук пыли, мелодия на фоне
https://drive.google.com/drive/folders/15Aj4tGkdY88fXJZKcxg9hHXtNShNWFE9

**Comment by epexa** [comment]
@arkhleb 👍🏽

**Comment by epexa** [comment]
**музыка для видео и сайта. можно несколько треков и даже целый плейлист составить:**

**Comment by epexa** [comment]
**[Bartosz Chajdecki - Wolność](https://drive.google.com/file/d/16X3Qe_xt4XDTCD4pyiPJtFsFIprreV6B/view)**

**Comment by epexa** [comment]
**[Bartosz Chajdecki - Warsaw Rising](https://drive.google.com/file/d/1SYJquQbnFsZExNSO0kjeu9-TgjyfHhUa/view)**

**Comment by epexa** [comment]
**[Bartosz Chajdecki - Determinacja](https://drive.google.com/file/d/1fIA8lsy9rbsBV3GtdGXqJKCkH-0sKKsU/view)**

**Comment by epexa** [comment]
**[Bartosz Chajdecki - Chce sie zyc](https://drive.google.com/file/d/1aBft8qXFd5KZr-kGjfTqHdEz0yRyGYcV/view)**

**Comment by epexa** [comment]
**[Epic Score - I Still Have a Soul](https://drive.google.com/file/d/1bybgarYAMy-YEaEse_P9wevj50zGfakC/view)**

**Comment by epexa** [comment]
**[Jamin Winans - John's Walk](https://drive.google.com/file/d/1DgzdVK6SfHlTU8qBp9u466qELtA2iiOy/view)**

**Comment by epexa** [comment]
**[Maxence Cyrin - Where Is My Mind](https://drive.google.com/file/d/1vcHa2Olh6aIyzy9C_8J3zds8jVvmcLZx/view)**

**Comment by epexa** [comment]
**[Amnesia - Oswald Mandus](https://drive.google.com/file/d/1OTxbh15X2gxot9YoHs5UPp35uXz346ZX/view)**

**Comment by epexa** [comment]
**[Hans Zimmer - Day One](https://drive.google.com/file/d/1UZ8spN-DW1i1kOZhnhuZyVkS4t6ASurO/view)**

**Comment by epexa** [comment]
**[Linkin Park - Numb (Piano)](https://drive.google.com/file/d/1fq0OF7KowSdJ2j8AJlV815Fpc9D0IJrs/view)**

**Comment by epexa** [comment]
**[Scorpions - Wind of Change (Piano)](https://drive.google.com/file/d/1hjqISPRSwF2rkUDol02RWDVWtXZhoIz4/view)**

**Comment by arkhleb** [comment]
@epexa отлично, но надо учитывать,  что если будем монетизация потом превратится в комерческий надо будет убирать некотрые??  Кстати что если мы тогда уж польского Владислава Шпильмана поставим,  он пианист,  фильм Пианист снят по его тяжелой биографии,  смотрели польский???  Или Шопена преславутого??

**Comment by epexa** [comment]
**[Nirvana - Smells like Teen Spirit (Piano)](https://drive.google.com/file/d/1gfxCW9XI9Q1Qi1BCX1jwyNn2cfIc7OiC/view)**
