### ISSUE TITLE
Правки по сайту

### ISSUE THREAD

**Issue by knopf127** [epexa/forestspace.eu#36]
- [x] Скрыть аудиодорожку визуально, которая на карте гугла - оставить плей-стоп визуально.
- [x] Аудиодорожка должна начинаться с момента как земля начинает крутиться.
- [x] Вместо кнопки - Выйти - написать: Вернуться в окно(можешь еще придумать другое название).
- [x] Синхронизировать текст с аудиодорожкой в мифах.
- [x] Шрифт для текста мифа.

**Comment by epexa** [comment]
#30 шрифт
