### ISSUE TITLE
Мистика. Разработка персонажей - отображающих собой легенды пущи.

### ISSUE THREAD

**Issue by arkhleb** [epexa/forestspace.eu#9]
Иллюстрация, 
![referens_1](https://user-images.githubusercontent.com/41944937/43446812-840f1bf2-94b2-11e8-8048-ade787cfe9b6.jpg)
![1832a80a8fcad294df85ceccd3b458a6](https://user-images.githubusercontent.com/41944937/43446813-842cc2ec-94b2-11e8-9a27-a0ab9ab5ab8b.jpg)
![fc6fc3f1e6afa884347dd1258227c59c](https://user-images.githubusercontent.com/41944937/43446814-844b31be-94b2-11e8-9e00-a83ca2a7764a.jpg)
![referens](https://user-images.githubusercontent.com/41944937/43446815-84667474-94b2-11e8-931b-a6e5ff42db78.jpg)

анимация

**Comment by epexa** [comment]
@arkhleb 

> Иллюстрация,

**последняя супер! только вот если сделать не в синем, а в зеленом...**
![43446815-84667474-94b2-11e8-931b-a6e5ff42db78](https://user-images.githubusercontent.com/2198826/43446984-05e0e5a2-94b3-11e8-8fa4-a7fd4585ccac.jpg)

**Comment by arkhleb** [comment]
@epexa хорошо, сделаю ближе к зеленому
